### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by TomasEliz**

### CODE REVIEW

**Review by ciamac-da — CHANGES_REQUESTED** [review]
Hey Tomas:) Good Job! But there is an error in last line! after console.log(firstName
 you have to use + instead of , means   +" "+  or   +' '+

**Comment by TomasEliz** [comment]
Hey Ciamac, thanks for the feedback!
Can you pls explain why is that an error? Because the result in terminal
looks the same as if I use " ", i.e. there is space between names anyway.

**Comment by ciamac-da** [comment]
Actually not an error:) I mean following exercise roles. You had to combine variables using + symbol and not , symbol.

**Comment by TomasEliz** [comment]
Alright then:)
Thanks for making this clear to me!

**Comment by ciamac-da** [comment]
No Prob.)

**Pull request merged**
